services:
  - type: web
    name: qhfixed-backend
    runtime: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: quickhire
      - key: REDIS_URL
        sync: false
      - key: JWT_PRIVATE_KEY
        sync: false
      - key: JWT_PUBLIC_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: RS256
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_TTL
        value: 30d
      - key: JWT_ISSUER
        value: quickhire.services
      - key: JWT_AUDIENCE
        value: quickhire-api
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: SMS_PROVIDER
        value: mock
      - key: DEV_MASTER_OTP
        value: "1234"
      - key: OTP_LENGTH
        value: "4"
      - key: OTP_TTL_SECONDS
        value: "300"
      - key: DISABLE_QUEUE_WORKERS
        value: "true"
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_PER_MIN
        value: "120"
      - key: APP_VERSION
        value: "1.0.0"
      - key: SES_FROM
        value: no-reply@quickhire.services
